apiVersion: v1
kind: Service
metadata:
  name: postechallenge-api
  namespace: postechallenge
  labels:
    app: postechallenge-api
spec:
  selector:
    app: postechallenge-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
      name: http
