services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:?Defina MSSQL_SA_PASSWORD no .env}"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD:?Defina MSSQL_SA_PASSWORD no .env}"
      MSSQL_PID: Developer
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -No -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 20
      start_period: 120s
    security_opt:
      - no-new-privileges:true

  sql-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./infra/sql/init.sql:/usr/config/init.sql
    environment:
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:?Defina MSSQL_SA_PASSWORD no .env}"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD:?Defina MSSQL_SA_PASSWORD no .env}"
      APP_DB_PASSWORD: "${APP_DB_PASSWORD:?Defina APP_DB_PASSWORD no .env}"
    user: root
    networks:
      - backend
    entrypoint:
      - /bin/bash
      - -ec
      - |
        echo 'Aguardando 10 segundos para estabilizacao final...'
        sleep 10
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P "$$MSSQL_SA_PASSWORD" -No -v APP_DB_PASSWORD="$$APP_DB_PASSWORD" -i /usr/config/init.sql
        echo 'Script de criacao executado com sucesso!'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postechallenge-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT:-Production}"
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PosTechChallenge;User Id=appchat;Password=${APP_DB_PASSWORD:?Defina APP_DB_PASSWORD no .env};TrustServerCertificate=True;"
      Jwt__SecretKey: "${JWT_SECRET_KEY:?Defina JWT_SECRET_KEY no .env}"
      Jwt__Issuer: "PosTechChallenge"
      Jwt__Audience: "PosTechChallenge-API"
      Jwt__AccessTokenExpirationMinutes: "15"
    depends_on:
      sql-init:
        condition: service_completed_successfully
    networks:
      - backend

volumes:
  sqlserver-data:
    driver: local

networks:
  backend:
    driver: bridge
