<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>false</PublishAot>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />

		<PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />

		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="7.2.0" />

		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
	</ItemGroup>

  <ItemGroup>
	  
    <ProjectReference Include="..\PosTechChallenge.Applicacao\PosTechChallenge.Aplicacao.csproj" />
    <ProjectReference Include="..\PosTechChallenge.Infraestrutura\PosTechChallenge.Infraestrutura.csproj" />
  </ItemGroup>
  
</Project>
