apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: postechallenge
  labels:
    app: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      name: mssql
  clusterIP: None  # Headless service para StatefulSet
